apiVersion: v1
kind: Service
metadata:
  name: einstein-service
  labels:
    app: einstein-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: einstein